---
- name: Rebuild github-runner
  community.docker.docker_compose_v2:
    project_src: "{{ github_runner_config_path }}"
    state: present
    build: always

- name: Restart github-runner
  community.docker.docker_compose_v2:
    project_src: "{{ github_runner_config_path }}"
    state: restarted
