---
- name: Add all hosts to known_hosts on localhost
  hosts: localhost
  tasks:
    - name: Add to known_hosts
      ansible.builtin.known_hosts:
        name: "{{ item.ansible_host }}"
        state: present
        key:
          "{{ lookup('pipe', 'ssh-keyscan -t ed25519 -p ' ~ item.ansible_port ~ '
          ' ~ item.ansible_host ~ ' ' ~ '| grep -i ed25519') }}"
      loop: "{{ groups['all'] | map('extract', hostvars) | list }}"
